apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
      - name: testdep
        # image: k8s.gcr.io/echoserver:1.4
        image: gcr.io/google-samples/kubernetes-bootcamp:v1
        ports:
        - containerPort: 80